// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// See: https://leetcode.com/problems/find-the-difference/
// See: https://leetcode.com/problems/find-the-difference/discuss/598348/Java-Fast-and-Concise

package leetcode.array_and_hashtable;

public class FindTheDifference {
   
    public char findTheDifference(String s, String t) {
        int[] alphabet = new int[26];
        for (int i = 0; i < s.length(); i++) {
            alphabet[s.charAt(i) - 'a']++;
            alphabet[t.charAt(i) - 'a']--;
        }
        
        for (int i = 0; i < alphabet.length; i++)
            if (alphabet[i] == -1) return (char)(i + 'a');

        return t.charAt(t.length() - 1);
    }
        
    public char findTheDifference_var1(String s, String t) {
        int[] alphabet = new int[26];
        for (int i = 0; i < s.length(); i++)
            alphabet[s.charAt(i) - 'a']++;
        
        for (int i = 0; i < t.length(); i++) {
            if (alphabet[t.charAt(i) - 'a'] == 0)
                return t.charAt(i);
            else 
                alphabet[t.charAt(i) - 'a']--;
        }
        
        return '\0';
    }
    
    public static void main(String[] args) {
        FindTheDifference sln = new FindTheDifference();
        
        System.out.println(sln.findTheDifference("abcd", "abcde"));
        System.out.println(sln.findTheDifference("abcd", "eabcd"));
        System.out.println(sln.findTheDifference("abcd", "abecd"));
        System.out.println(sln.findTheDifference("aaabbb", "aaabbbe"));
    }

}
